# Generated by Django 4.1.7 on 2023-05-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('afinacion', models.CharField(max_length=180)),
                ('link_youtube', models.CharField(max_length=180)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CapturaCancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=180)),
                ('imagen', models.FileField(upload_to='uploads')),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
