# Generated by Django 4.1.7 on 2023-05-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturacancion',
            name='imagen',
            field=models.CharField(max_length=180),
        ),
    ]
