# Generated by Django 4.1.7 on 2023-05-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_capturacancion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturacancion',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
