# Generated by Django 4.1.7 on 2023-05-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_capturacancion_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturacancion',
            name='cancion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.cancion'),
        ),
    ]
