# Generated by Django 4.1.7 on 2023-06-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_capturacancion_cancion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='dificultad',
            field=models.CharField(default='', max_length=180),
        ),
    ]
